### ISSUE TITLE
New azure_rm hashicorp latest version issue

### ISSUE THREAD

**Issue by Nikhleshk** [gettek/terraform-azurerm-policy-as-code#15]
resource "azurerm_resource_policy_remediation" "example" {
  name                 = "remediation1"
  resource_id          = azurerm_virtual_network.example.id
  policy_assignment_id = azurerm_resource_group_policy_assignment.test.id
}

hashicorp azure_rm(latest) has replaced azurerm_policy_remediation to above azurerm_resource_policy_remediation which requires resource_id as mandatory parameter .
Can you please suggest what should be the value used here?

**Comment by gettek** [comment]
Hi @Nikhleshk 

For now I suggest restricting your provider version to `<=2.99.0` until #13 is resolved:

```hcl
provider "azurerm" {
  version = "<=2.99.0"
  features {}
}
```
Or from the Terraform block:
```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	  version = "<=2.99.0"
    }
  }
}
```

If you wish to use the newer provider `>=3.0.0` you should specify `skip_remediation=true` then create a remediation resource manually:

```hcl
module "team_a_mg_inherit_resource_group_tags_modify" {
  source            = "..//modules/def_assignment"
  definition        = module.inherit_resource_group_tags_modify.definition
  assignment_scope  = data.azurerm_management_group.team_a.id
  assignment_effect = "Modify"
  skip_remediation  = true
  assignment_parameters = {
    tagName = "environment"
  }
}

resource "azurerm_management_group_policy_remediation" "example" {
  name                 = "exampleRemediation"
  management_group_id  = data.azurerm_management_group.team_a.id
  policy_assignment_id = module.team_a_mg_inherit_resource_group_tags_modify.id
}
```

**Comment by Nikhleshk** [comment]
Hi Sadik,

Thanks for the response.
One more question i wanna ask is there any specific format for json file in
policy.
Because I have one private link dns A record policy and definition is not
getting deployed as it should be in portal.

Br
Nikhlesh

**Comment by Nikhleshk** [comment]
Even can you share template structure of JSON file,so i can make necessary changes on my policy structure.After this i think terraform will be able to read my JSON files

**Comment by gettek** [comment]
The definitions module takes in standard policyDefinition json schema as seen in the [variables file](https://github.com/gettek/terraform-azurerm-policy-as-code/blob/main/modules/definition/variables.tf#L81-L93). There are a bunch of examples under the [policies](https://github.com/gettek/terraform-azurerm-policy-as-code/tree/main/policies) folder but you are not restricted to using this module for custom definitions.

**Comment by Nikhleshk** [comment]
"properties": {
    "displayName": "Private Link Azure Cache for Redis A-record to private DNS Zone",
    "policyType": "Custom",
    "mode": "Indexed",
    "description": "DeployIfNotExists policy to automatically create the required DNS record in the central private DNS zone.\nhttps://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale#configuration-required-by-platform-team",
    "metadata": {
      "category": "Private Link"
    },
    "parameters": {
      "privateDnsZoneId": {
        "type": "String",
        "metadata": {
          "displayName": "privateDnsZoneId",
          "description": null,
          "strongType": "Microsoft.Network/privateDnsZones"
        }
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Network/privateEndpoints"
          },
          {
            "count": {
              "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
              "where": {
                "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
                "equals": "redisCache"
              }
            },
            "greaterOrEquals": 1
          }
        ]
      },
      "then": {
        "effect": "deployIfNotExists",
        "details": {
          "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",
          "roleDefinitionIds": [
            "/providers/Microsoft.Authorization/roleDefinitions/befefa01-2a29-4197-83a8-272ff33ce314",
            "/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7"
          ],
          "deployment": {
            "properties": {
              "mode": "incremental",
              "template": {
                "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {
                  "privateDnsZoneId": {
                    "type": "string"
                  },
                  "privateEndpointName": {
                    "type": "string"
                  },
                  "location": {
                    "type": "string"
                  }
                },
                "resources": [
                  {
                    "name": "[concat(parameters('privateEndpointName'), '/deployedByPolicy')]",
                    "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",
                    "apiVersion": "2020-03-01",
                    "location": "[parameters('location')]",
                    "properties": {
                      "privateDnsZoneConfigs": [
                        {
                          "name": "redisCache-privateDnsZone",
                          "properties": {
                            "privateDnsZoneId": "[parameters('privateDnsZoneId')]"
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              "parameters": {
                "privateDnsZoneId": {
                  "value": "[parameters('privateDnsZoneId')]"
                },
                "privateEndpointName": {
                  "value": "[field('name')]"
                },
                "location": {
                  "value": "[field('location')]"
                }
              }
            }
          }
        }
      }
    }

In this terrafrom is not able to find effect   "effect": "deployIfNotExists",

**Comment by Nikhleshk** [comment]
Yes at the end made few changes in policies only to make it work according to the terraform file.
But now facing challenges in role definition ids.
I want that terraform file should fetch automatically from the json file for initiative or single policy(even when initiatives consists of policies with different role definition ids).
Is there any way to automate this?????
I tried but no luck

**Comment by gettek** [comment]
@Nikhleshk as mentioned in the main README file:

💡 **Note:** The required [Role Definitions](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources#configure-policy-definition) for the System Assigned Identity will be scoped at the policy assignment by default, you can override these [as seen here](https://github.com/gettek/terraform-azurerm-policy-as-code/tree/main/examples/assignments_org.tf#L51-L54) or specify `skip_role_assignment=true` to omit creation.

Assignments made using the `def_assignment` module automatically create the role assignments

**Comment by Nikhleshk** [comment]
module "team_a_mg_inherit_resource_group_tags_modify" {
  source            = "..//modules/def_assignment"
  definition        = module.inherit_resource_group_tags_modify.definition
  assignment_scope  = data.azurerm_management_group.team_a.id
  assignment_effect = "Modify"
  skip_remediation  = true
  assignment_parameters = {
    tagName = "environment"
  }
}

resource "azurerm_management_group_policy_remediation" "rem" {
  for_each = { for dr in local.definition_reference : basename(dr.policy_definition_id) => dr }
  name     = lower("${each.key}-${formatdate("DD-MM-YYYY-hh:mm:ss", timestamp())}")
 # name                 = "exampleRemediation"
  management_group_id  = data.azurerm_management_group.org.id
  policy_assignment_id    = local.assignment_id
  #policy_assignment_id = module.org_mg_configure_asc_initiative.id
  depends_on = [azurerm_role_assignment.rem_role]
}

Trying by this but remediation task not taking even a single step

**Comment by gettek** [comment]
@Nikhleshk have you tried parameterising the effect within the definition?

[see this example](https://github.com/gettek/terraform-azurerm-policy-as-code/blob/main/policies/General/whitelist_resources.json#L20:L32)
