### ISSUE TITLE
Defining initiative

### ISSUE THREAD

**Issue by Nikhleshk** [gettek/terraform-azurerm-policy-as-code#19]
I Am really confuse while defining initiative for given below

{
    "type": "Microsoft.Authorization/policySetDefinitions",
    "name": "Azure-Tags",
    "properties": {
        "displayName": "Append and Inherit Tags from Resource Group",
        "description": "Append and Inherit Tags from Resource Group",
        "metadata": {
            "category": "Tags"
        },
        "parameters": {
            "Add-mandatory-tags-on-Resource-Groups_tagName": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "serviceprovider"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagValue": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Value (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "tbd"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagName1": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "environment"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagValue1": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Value (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "tbd"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagName2": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "project number"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagValue2": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Value (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "tbd"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagName3": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "guid"
            },
            "Add-mandatory-tags-on-Resource-Groups_tagValue3": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Value (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "tbd"
            },
            "Append-Patching-tag-with-default-value-for-VMs_tagName": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Append Patching tag with default value for VMs)"
                },
                "defaultValue": "patching"
            },
            "Append-Patching-tag-with-default-value-for-VMs_tagValue": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Value (Policy: Append Patching tag with default value for VMs)"
                },
                "defaultValue": "default"
            },
            "Inherit-tags-from-the-resource-group_tagName": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "serviceprovider"
            },
            "Inherit-tags-from-the-resource-group_tagName1": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "environment"
            },
            "Inherit-tags-from-the-resource-group_tagName2": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "project number"
            },
            "Inherit-tags-from-the-resource-group_tagName3": {
                "type": "string",
                "metadata": {
                    "displayName": "Tag Name (Policy: Add mandatory tags on Resource Groups)"
                },
                "defaultValue": "guid"
            }
        },
        "policyDefinitions": [
            {
                "policyDefinitionId": "{policyLocationResourceId1}/providers/Microsoft.Authorization/policyDefinitions/Add-mandatory-tags-on-Resource-Groups",
                "parameters": {
                    "tagName": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagName')]"
                    },
                    "tagValue": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagValue')]"
                    },
                    "tagName1": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagName1')]"
                    },
                    "tagValue1": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagValue1')]"
                    },
                    "tagName2": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagName2')]"
                    },
                    "tagValue2": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagValue2')]"
                    },
                    "tagName3": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagName3')]"
                    },
                    "tagValue3": {
                        "value": "[parameters('Add-mandatory-tags-on-Resource-Groups_tagValue3')]"
                    }
                },
                "groupNames": []
            },
            {
                "policyDefinitionId": "{policyLocationResourceId1}/providers/Microsoft.Authorization/policyDefinitions/Append-Patching-tag-with-default-value-for-VMs",
                "parameters": {
                    "tagName": {
                        "value": "[parameters('Append-Patching-tag-with-default-value-for-VMs_tagName')]"
                    },
                    "tagValue": {
                        "value": "[parameters('Append-Patching-tag-with-default-value-for-VMs_tagValue')]"
                    }
                },
                "groupNames": []
            },
            {
                "policyDefinitionId": "{policyLocationResourceId1}/providers/Microsoft.Authorization/policyDefinitions/Inherit-tags-from-the-resource-group",
                "parameters": {
                    "tagName": {
                        "value": "[parameters('Inherit-tags-from-the-resource-group_tagName')]"
                    },
                    "tagName1": {
                        "value": "[parameters('Inherit-tags-from-the-resource-group_tagName1')]"
                    },
                    "tagName2": {
                        "value": "[parameters('Inherit-tags-from-the-resource-group_tagName2')]"
                    },
                    "tagName3": {
                        "value": "[parameters('Inherit-tags-from-the-resource-group_tagName3')]"
                    }
                },
                "groupNames": []
            }
        ],
        "policyDefinitionGroups": []
    }
}

**Comment by gettek** [comment]
I suggest you return and read the module documentation as this is not a clear enough issue
