### ISSUE TITLE
Suppose i have one initiative in which Deny,Audit and AuditifNotexists effects are there for policies.How to pass in assignment_effect in assignment.org??

### ISSUE THREAD

**Issue by Nikhleshk** [gettek/terraform-azurerm-policy-as-code#20]
# Issue Template

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Module Version:
* Terraform Version:
* AzureRM Provider Version:

### Steps to Reproduce

1.
2.
3.

**Comment by gettek** [comment]
@Nikhleshk as mentioned in the main repository [readme](https://github.com/gettek/terraform-azurerm-policy-as-code#policy-initiative-set-definitions-module):

> If any two member_definition_ids contain the same parameters then they will be merged() by this module, in most cases this is beneficial but if unique values are required it may be best practice to set unique keys such as [parameters('whitelist_resources_effect')] instead of [parameters('effect')].

**Comment by timwebster9** [comment]
Do you mean changing the parameter name in the policy definitions?

If that's not what you mean, and there is a way to map parameters in the policy definition to parameters in each individual policy then can you provide an example in your readme or in the examples section?

**Comment by gettek** [comment]
> Do you mean changing the parameter name in the policy definitions?

In short, yes. If mixed values are required during assignment it would be best practice to change the parameter name within each definition such as `"whitelist_resources_effect"` instead of `"effect"`

**Comment by gettek** [comment]
@timwebster9 
> Do you mean changing the parameter name in the policy definitions?

In short, yes. If mixed values are required during assignment it would be best practice to change the parameter name within each definition such as `"whitelist_resources_effect"` instead of `"effect"`

**Comment by timwebster9** [comment]
hmm actually I'd say it's pretty much a requirement to be able to map custom parameters in the initiative definition.  We use a lot of built-in policies that we can't change the parameter names for.  I know that creating a custom version of the policy is an option, but we've moved away from doing that.

**Comment by jesseloudon** [comment]
We are also mixing built-in and custom definitions in the 1 initiative because it often makes sense to not duplicate what is already available in Azure. I was able to update the initiative module in this repo to have 'unique-ness' for each parameter reference within the **policy definition reference**. 

Basically using **format()** to combine the **parameter name** with the **policy definition's reference ID** to produce a string which prevents definitions with the same parameter names (effect is a common example) from being combined and producing an error when the parameter's allowed values are different (DINE vs Modify, etc). I'm sure there's better/more elegant ways to do this 😄 

```hcl
  dynamic policy_definition_reference {
    for_each = [for d in var.member_definitions : {
      id         = d.id
      ref_id     = substr(title(replace(d.name, "/-|_|\\s/", " ")), 0, 64)
      parameters = jsondecode(d.parameters)
      groups     = []
    }]

    content {
      policy_definition_id = policy_definition_reference.value.id
      reference_id         = replace(policy_definition_reference.value.ref_id, "/\\s/", "")
      parameter_values = jsonencode({
        for k in keys(policy_definition_reference.value.parameters) :
        k => { value = "[parameters('${format("%s_%s", k, replace(policy_definition_reference.value.ref_id, "/\\s/", ""))}')]" }
      })
      policy_group_names = policy_definition_reference.value.groups
    }
  }
```

The remaining uplift to do (which I haven't figured out how) is for the initiative's local parameters to do something similar as above.

```hcl
parameters = jsonencode(local.parameters) #Need to uplift so parameter name is unique for each definition and includes the definition reference ID in the parameter name.
```
