### ISSUE TITLE
Support for custom policies not defined in policies directory

### ISSUE THREAD

**Issue by przemekp** [gettek/terraform-azurerm-policy-as-code#24]
# Issue Template

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Module Version: 2.5.1
* Terraform Version: 1.2.2
* AzureRM Provider Version: 3.2.0

## Expected Behavior

Ability to create custom policies that are not declared in policies directory. 

## Current Behavior

Custom policies requires a file with definition to be present in policies directory:
```
  policy_object = jsondecode(file("${path.module}/../../policies/${title(var.policy_category)}/${var.policy_name}.json"))
``` 
This limits options of available custom policies. 

## Possible Solution

1. Add a variable defining path to a file containing custom policy definition. Therefore I could reference custom policies outside of module.
2. Or add a special dummy policy that can be used as a template. Then just replace all parameters using variables: policy_metadata, policy_rule, policy_parameters, policy_name.

### Steps to Reproduce

1. Create custom policy that is not defined in policies directory
2. Run terraform plan

**Comment by gettek** [comment]
@przemekp this will be fixed in #23

**Comment by gettek** [comment]
BTW, these parameters exist in 2.5.1 also. [See Definition Inputs](https://github.com/gettek/terraform-azurerm-policy-as-code/tree/main/modules/definition#inputs)

**Comment by przemekp** [comment]
@gettek Could you provide example of policy_rule  passed as a variable? I get error error inconsistent conditional result types. Still, I think that adding variable for file path would streamline use of custom policies, right now, custom policy name and file are bound to each other, so even if I modify whole policy content (by policy_rule) I am stuck with odd policy name.

**Comment by gettek** [comment]
Hi @przemekp 

After some testing you are correct `local.policy_object` should have been wrapped around a try block to successfully omit the local library path. I will also add `var.file_path` as an input option to achieve the below:

```hcl
module "file_path_test" {
  source              = "..//modules/definition"
  policy_name         = "file_path_test"
  file_path           = "onboard_to_automation_dsc_linux.json"
  management_group_id = data.azurerm_management_group.org.id
}
```

You will also be able to supply object properties at runtime such as:
```hcl
locals {
  policy_file = jsondecode(file("onboard_to_automation_dsc_linux.json"))
}
module "parameterised_test" {
  source              = "..//modules/definition"
  policy_name         = "parameterised_test"
  display_name        = (local.policy_file).properties.displayName
  policy_description  = (local.policy_file).properties.description
  policy_category     = (local.policy_file).properties.metadata.category
  management_group_id = data.azurerm_management_group.org.id

  policy_rule             = (local.policy_file).properties.policyRule
  policy_parameters = (local.policy_file).properties.parameters
  policy_metadata    = (local.policy_file).properties.metadata
}

```
