### ISSUE TITLE
remediation task not working as expected

### ISSUE THREAD

**Issue by Nikhleshk** [gettek/terraform-azurerm-policy-as-code#27]
Used this code in assignmemt.org

module "org_mg_Network-Watcher_initiative" {
  source               = "..//modules/set_assignment"
  initiative           = module.Network-Watcher_initiative.initiative
  assignment_scope     = data.azurerm_management_group.org.id
  assignment_effect    = "DeployIfNotExists"
  skip_remediation     = false
  skip_role_assignment = false
   role_definition_ids  = module.Network-Watcher_initiative.role_definition_ids
  assignment_parameters = {
    effect1 = "AuditIfNotExists"
    listOfLocations = [
      "WestEurope",
      "NorthEurope",
      "EastUS"
    ]
  }
}

Policy is getting assigned properly but remediation not as expected.
![Capture](https://user-images.githubusercontent.com/46476993/173076625-3748672f-138b-4ad5-94c4-1945f41c26a7.PNG)

**Comment by gettek** [comment]
closing duplicate issue #28
