### ISSUE TITLE
Why we can't see remediation in affect after executing the code

### ISSUE THREAD

**Issue by ashuranjan1008** [gettek/terraform-azurerm-policy-as-code#28]
Hi,

Inspite of successful run of the policy, I am not getting the remediation task.

![image](https://user-images.githubusercontent.com/104419962/173554247-698469df-a184-4e06-a95c-4a11b0af75a7.png)

**Comment by gettek** [comment]
Hi @ashuranjan1008 

What is the compliance state of this assignment? Remediations will only be created for non compliant resources

**Comment by ashuranjan1008** [comment]
Hi @gettek,

Even though I am having non compliant recourses, but still task is not showing.

![image](https://user-images.githubusercontent.com/104419962/173600665-8bdd9cce-5b3e-45e7-becc-3411b9559884.png)

**Comment by gettek** [comment]
@ashuranjan1008 can you please try and create a remediation task outside of the module using the [native resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_management_group_policy_remediation) and see what happens?

**Comment by ashuranjan1008** [comment]
@gettek I can see remediation task getting created while running single policy but, when I try to do the same while taking initiative it doesn't work in the same way.
 
 
![image](https://user-images.githubusercontent.com/104419962/174305559-096acf62-a74a-44cb-9f5b-1b64f2909e23.png)
