### ISSUE TITLE
Additional policy metadata not saved

### ISSUE THREAD

**Issue by timwebster9** [gettek/terraform-azurerm-policy-as-code#32]
# Issue Template

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Module Version: 2.6.0
* Terraform Version: 1.2.3
* AzureRM Provider Version: 3.10.0

```hcl
    "metadata": {
      "version": "1.0.0",
      "category": "Batch",
      "propertyA": "A",
      "propertyB": "B
    },
```

## Expected Behavior
Anything included in the 'metadata' object should be saved to the policy definition

## Current Behavior
Any additional metadata besides 'version' and 'category' won't be saved in the policy definition.  In the above snippet, 'propertyA' and 'propertyB' won't be saved.

## Possible Solution
I think the problem lies here: https://github.com/gettek/terraform-azurerm-policy-as-code/blob/531e5425c6d4584cbeac8c1019cc2a93629f0ffb/modules/definition/variables.tf#L100

local.category and local.version will always be populated due to the logic on lines 91 and 92.  Since they will be populated, the coalesce function on line 100 will always return the 2nd argument, which is the merge of category and version.  The 3rd argument (the metadata in the policy file itself) will never get used.  This is assuming you don't provide a var.policy_metadata variable.

Also, I tried putting all the metadata into the var.policy_metadata variable instead, but then got an error about not all objects being the same type in the coalesce function, I guess because category and version are strings and policy_metadata is an object.

### Steps to Reproduce

1. Write a policy definition with additional metadata
2. Deploy it using the 'definitions' module
3. observe that only 'category' and 'version' fields of the metadata are present in the policy definition when viewed in the Azure portal.

**Comment by gettek** [comment]
Hi @timwebster9, I have tried to recreate this issue with no luck could you please paste a snippet of your metadata. The module  uses the jsonencode() function so no need for additional wrappers; here is the code I tested:

```hcl
module "whitelist_regions" {
  source              = "..//modules/definition"
  policy_name         = "whitelist_regions"
  display_name        = "Whitelist Azure Regions"
  policy_category     = "General"
  management_group_id = data.azurerm_management_group.org.id

  policy_metadata = {
    version   = "1.0.0"
    category  = "Batch"
    propertyA = "A"
    propertyB = "B"
  }
}
```

Plan Output:
```bash
# module.whitelist_regions.azurerm_policy_definition.def will be created
  + resource "azurerm_policy_definition" "def" {
      + description         = "Whitelist Regions"
      + display_name        = "Whitelist Azure Regions"
      + id                  = (known after apply)
      + management_group_id = "/providers/Microsoft.Management/managementGroups/policy_dev"
      + metadata            = jsonencode(
            {
              + category  = "Batch"
              + propertyA = "A"
              + propertyB = "B"
              + version   = "1.0.0"
            }
        )
```

Definition as viewed in the portal:
```json
    "metadata": {
      "category": "Batch",
      "propertyA": "A",
      "propertyB": "B",
      "version": "1.0.0",
      "createdBy": "zzzzzz",
      "createdOn": "2022-06-21T21:32:04.7388749Z",
      "updatedBy": null,
      "updatedOn": null
    },
```

**Comment by gettek** [comment]
Thanks @timwebster9 the fallback will be moved to its correct position within coalesce() in the next release

**Comment by timwebster9** [comment]
thanks @gettek.  If we need to supply custom metadata, what approach do you recommend?:

1.  put the entire metadata object in the policy .json file
2. put the entire metadata object in var.policy_metadata
3. populate var.policy_category and var.policy_version, and the custom metadata in the .json file or var.policy_metadata?

**Comment by gettek** [comment]
I'd put common ones in the `definition.json`, anything you parse into `var.policy_metadata` will intentionally override these at runtime after this fix, as well as `var.assignment_metadata` if the attributes need to be different at assignment or omit to use the same.
