### ISSUE TITLE
Terraform apply not working with different policy_mode

### ISSUE THREAD

**Issue by Nikhleshk** [gettek/terraform-azurerm-policy-as-code#34]
```json
{
    "type": "Microsoft.Authorization/policyDefinitions",
    "name": "Key-Vault-secrets-should-have-expiration-date",
    "properties": {
      "displayName": "Key Vault secrets should have an expiration date",
      "policyType": "Custom",
      "mode": "Microsoft.KeyVault.Data",
      "description": "Secrets should have a defined expiration date and not be permanent. Secrets that are valid forever provide a potential attacker with more time to compromise them. It is a recommended security practice to set expiration dates on secrets.",
      "metadata": {
        "version": "1.0.2",
        "category": "Key Vault"
      },
      "parameters": {
        "effect": {
          "type": "String",
          "metadata": {
            "displayName": "Effect",
            "description": "'Audit' allows a non-compliant resource to be created, but flags it as non-compliant. 'Deny' blocks the resource creation. 'Disable' turns off the policy."
          },
          "allowedValues": [
            "Audit",
            "Deny",
            "Disabled"
          ],
          "defaultValue": "Audit"
        }
      },
      "policyRule": {
        "if": {
          "allOf": [
            {
              "field": "type",
              "equals": "Microsoft.KeyVault.Data/vaults/secrets"
            },
            {
              "field": "Microsoft.KeyVault.Data/vaults/secrets/attributes.expiresOn",
              "exists": false
            }
          ]
        },
        "then": {
          "effect": "[parameters('effect')]"
        }
      }
    }
  }
```

This is the policy with different mode.Plan is successful. But during apply getting below error
 Error: creating/updating Policy Definition "Key-Vault-secrets-should-have-expiration-date": policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidProviderNameInPolicyAlias" Message="The policy definition 'Key-Vault-secrets-should-have-expiration-date' rule is invalid. The provider 'Microsoft.KeyVault.Data' referenced by the 'field' property 'Microsoft.KeyVault.Data/vaults/secrets/attributes.expiresOn' of the policy rule doesn't exist."
│ 
│   with module.Key-Vault["Key-Vault-secrets-should-have-expiration-date"].azurerm_policy_definition.def,
│   on ..\..\modules\definition\main.tf line 1, in resource "azurerm_policy_definition" "def":
│    1: resource azurerm_policy_definition def {
│ 
╵
╷
│ Error: creating/updating Policy Definition "Key-Vault-keys-should-have-expiration-date": policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidProviderNameInPolicyAlias" Message="The policy definition 'Key-Vault-keys-should-have-expiration-date' rule is invalid. The provider 'Microsoft.KeyVault.Data' referenced by the 'field' property 'Microsoft.KeyVault.Data/vaults/keys/attributes.expiresOn' of the policy rule doesn't exist."
│ 
│   with module.Key-Vault["Key-Vault-keys-should-have-expiration-date"].azurerm_policy_definition.def,
│   on ..\..\modules\definition\main.tf line 1, in resource "azurerm_policy_definition" "def":
│    1: resource azurerm_policy_definition def {

Not able to resolve

**Comment by gettek** [comment]
I have ran tests with both the built-in and custom definitions and can confirm the built-in works due to the Mode having more permissions to view `Microsoft.KeyVault.Data`.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/14080406/177196043-506b9697-7549-466a-8262-0605a2d9d515.png">

When I try to create the custom definition with the same mode I receive the below error:
```hcl
module "keyvault_secret_expiration" {
  source              = "..//modules/definition"
  policy_name         = "keyvault_secret_expiration"
  policy_category     = "Key Vault"
  policy_mode         = "Microsoft.KeyVault.Data"
  management_group_id = data.azurerm_management_group.org.id
}

module "team_a_mg_keyvault_secret_expiration" {
  source            = "..//modules/def_assignment"
  definition        = module.keyvault_secret_expiration.definition
  assignment_scope  = data.azurerm_management_group.team_a.id
  assignment_effect = "Audit"
}
```
> Error: creating/updating Policy Definition "keyvault_secret_expiration": policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyDefinitionMode" Message="The creation of custom policy definition using mode 'Microsoft.KeyVault.Data' is not allowed. This mode is allowed only in built-in policy definitions."

You can however include any built-in definition (with restricted modes) to your custom initiatives as seen in [this example](https://github.com/gettek/terraform-azurerm-policy-as-code/tree/main/modules/initiative#create-an-initiative-with-a-mix-of-custom--built-in-policy-definitions-without-merging-effects)

```hcl
data "azurerm_policy_definition" "key_vault_secret_exp_builtin" {
  name = "98728c90-32c7-4049-8429-847dc0f4fe37"
}
```

**Comment by Nikhleshk** [comment]
Thanks it worked :)
