### ISSUE TITLE
Multiple identical Policy Definitions in Initiative

### ISSUE THREAD

**Issue by ashkuren** [gettek/terraform-azurerm-policy-as-code#37]
Hello,

I am pursuing a scenario where a custom initiative can have the same policy definition added multiple times. This gives unique `policyDefinitionReferenceId` ([reference](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/initiative-definition-structure#policy-definition-properties)) which later allows assignment of multiple parameters.

For example, below is an initiative which uses 2 built-in policy definitions to require a tag on resource group:
```json
{
  "properties": {
    "displayName": "Test Initiative",
    "policyType": "Custom",
    "metadata": {
      "category": "Tags",
      "version": "1.0.0"
    },
    "parameters": {
      "tag_1": {
        "type": "string",
        "metadata": {
          "displayName": "Tag 1"
        }
      },
      "tag_2": {
        "type": "string",
        "metadata": {
          "displayName": "Tag 2"
        }
      }
    },
    "policyDefinitions": [
      {
        "policyDefinitionReferenceId": "Require a tag on resource groups_1",
        "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/96670d01-0a4d-4649-9c89-2d3abc0a5025",
        "parameters": {
          "tagName": {
            "value": "[parameters('tag_1')]"
          }
        },
        "groupNames": []
      },
      {
        "policyDefinitionReferenceId": "Require a tag on resource groups_2",
        "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/96670d01-0a4d-4649-9c89-2d3abc0a5025",
        "parameters": {
          "tagName": {
            "value": "[parameters('tag_2')]"
          }
        },
        "groupNames": []
      }
    ],
    "policyDefinitionGroups": []
  },
  "type": "Microsoft.Authorization/policySetDefinitions",
  "name": "0077d380911646ceb173ba21"
}
```

At the first glance, according to the [documentation](https://registry.terraform.io/modules/gettek/policy-as-code/azurerm/latest/submodules/initiative) we can only pass a list of policy definitions and nothing else.

Can you suggest if this scenario is supported?

Thank you.

**Comment by gettek** [comment]
You can certainly achieve this with the [native provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_set_definition) resource but unfortunately the `initiative` module here does not currently support this functionality as it auto generates the `policyDefinitionReferenceId` based on the definition name.

**Comment by timwebster9** [comment]
I want to do this as well, but another problem with it is that all the policies in the initiative will have the same display name and there is no way to change it.  The only difference between them is the parameters.  Anyone looking at the compliance in the portal won't know the difference between each policy in the initiative.  This is an Azure limitation, not this module or Terraform. 

We have a policy for naming convention that would be good for this.  It's a single definition, but the parameters change for each Azure resource we apply it for.

**Comment by gettek** [comment]
An example within [this discussion](https://github.com/gettek/terraform-azurerm-policy-as-code/discussions/40) has a workaround which may help.
