### ISSUE TITLE
How to do custom metadata?

### ISSUE THREAD

**Issue by timwebster9** [gettek/terraform-azurerm-policy-as-code#39]
# Issue Template

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Module Version: 2.6.1
* Terraform Version: 1.2.7
* AzureRM Provider Version: 3.19.1

I need to add custom metadata fields.  In this case, it's:
```
"owner": "security"
```
but there may be more in the future.  However the default variable handling gets in the way here, causing the coalesce function to fail.

How do I simply add a new metadata field?

<img width="804" alt="image" src="https://user-images.githubusercontent.com/6548787/186404146-f6f221f7-e191-418e-96d9-22fe3055941a.png">

## Expected Behavior
The custom metadata field should be applied.

## Current Behavior
Terraform errors with this message:

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/6548787/186404331-c260b447-62af-4013-a75f-8dad7975912d.png">

## Possible Solution
The default values for category and version are messing up the metadata handling in the coalesce function.  I need a way to specify new metadata fields without those getting in the way.  Perhaps the defaults can be removed - it's fine by me if Azure throws an error if we forget to include it.

**Comment by gettek** [comment]
Hi @timwebster9,

The module handles [json conversion](https://github.com/gettek/terraform-azurerm-policy-as-code/blob/main/modules/definition/main.tf#L10) so you must enter key/value pairs as HCL in your configuration such as below:

```hcl
policy_metadata = {
  version = "1.0.0"
  category = "Network"
  owner   = "Security"
}
```

Hope this helps

**Comment by timwebster9** [comment]
thank you - that worked 👍
