### ISSUE TITLE
Add functionality listed in #TODO in the Initiative module

### ISSUE THREAD

**Issue by NikolaiKleppe** [gettek/terraform-azurerm-policy-as-code#52]
# Issue Template

## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Context

Hi, in the initiative module there's a todo list for `parameter_value.metadata.displayName should also contain definition reference if merge_effects == false`

https://github.com/gettek/terraform-azurerm-policy-as-code/blob/main/modules/initiative/variables.tf#L94 

This is a functionality I have a need for at the moment, otherwise duplicate parameters have identical names in the Azure portal:
![image](https://user-images.githubusercontent.com/7556264/193273299-453f5297-55f7-4410-9a4e-6356b17123c9.png)

When editing parameters in the initiative assignment it looks like this:
![image](https://user-images.githubusercontent.com/7556264/193273427-d2146a0d-2b96-43bc-80bd-5284edfb111d.png)

So I need the reference ID (or in my case, DisplayName) to be added to the parameter metadata:
![image](https://user-images.githubusercontent.com/7556264/193276926-273bc55d-e4df-4dc2-a9bb-354f10065066.png)

I've tried to implement a solution myself in the locals parameters block, but haven't figured it out yet.

Is this on the roadmap to add, if it's not too complicated to implement?

Thanks :) Really good module otherwise, by the way

**Comment by gettek** [comment]
Hi @NikolaiKleppe, I've also been struggling with this one for some time.

In the meantime you can output the `policy_definition_reference.parameter_values` to get the list of respective parameters that you can specify at assignment. Hope this helps

**Comment by NikolaiKleppe** [comment]
Hi, thanks :) 

I've done that as well and it works fine - It's more because of my use case, where I'm looking to configure individual parameters in the Portal instead of through Terraform (probably sounds counter intuitive, but makes more sense for my specific use case)

I'll try some more to fix it in the meantime

**Comment by NikolaiKleppe** [comment]
Maybe a step closer, but doesn't quite work
Just added another locals block to test, an additional for loop, notice the ```in parameter_value.metadata```


```hcl
  parameter_display_name = merge(values({
    for definition, params in local.member_parameters :
    definition => {
      for parameter_name, parameter_value in params :
        parameter_name => {
          for metadata_name, metadata_value in parameter_value.metadata :
            var.merge_parameters == false ? format("%s_%s", replace(substr(title(replace(definition, "/-|_|\\s/", " ")), 0, 120), "/\\s/", ""), metadata_name) :
            metadata_name => metadata_value
    }}})...)
```


One problem is that it changes the value on the wrong side of the equal sign

![image](https://user-images.githubusercontent.com/7556264/193352391-40b71dbb-066e-486d-8cf4-9ac17ad4df48.png)

For my case it should be the following on the right side of the equal sign: `KubernetesClusterPodsAndContainersShouldOnlyRunWithApprovedUserAndGroupIDs_SupplementalGroupRule`

Definition:
![image](https://user-images.githubusercontent.com/7556264/193352554-ea8ebacd-442d-403f-85eb-1fa778291588.png)


If you change ```in parameter_value.metadata``` to ```in parameter_value.metadata.displayName``` it fails on the for expression

And even if this did work you'd have to merge it with the ```parameters``` block too

Posting in case it gives you any additional ideas, I'm just kinda brute-forcing through tests

**Comment by NikolaiKleppe** [comment]
@gettek I have a solution for it now - The logic will replace only the displayName inside the metadata block.

I think it works even if merge_parameters == true, but you can take a look at it if you want. There might be other scenarios I'm not aware of that can cause issues

```hcl
  # combine all discovered definition parameters using interpolation
  parameters = merge(values({
    for definition, params in local.member_parameters :
    definition => {
      for parameter_name, parameter_value in params :
      # if do not merge effects -> suffix only effects with definition references
      parameter_name == "effect" && var.merge_effects == false ? format("%s_%s", replace(substr(title(replace(definition, "/-|_|\\s/", " ")), 0, 120), "/\\s/", ""), parameter_name) :
      # if do not merge parameters -> suffix all parameters with definition references
      var.merge_parameters == false ? format("%s_%s", replace(substr(title(replace(definition, "/-|_|\\s/", " ")), 0, 120), "/\\s/", ""), parameter_name) :

      # New:
      parameter_name => {
        for key_1, value_1 in parameter_value :
            key_1 => (key_1 == "metadata" ? merge(value_1, { displayName = format("%s_%s", replace(substr(title(replace(definition, "/-|_|\\s/", " ")), 0, 120), "/\\s/", ""), parameter_name) }) : value_1 )
      }
    }
  })...)
```

I'm using name instead of ID for my policies at the moment, so it looks a bit messy with the long variable names, but still:

![image](https://user-images.githubusercontent.com/7556264/193582551-94fcb3e4-1ba7-495f-b117-faccbb0ff17a.png)

Definition:
![image](https://user-images.githubusercontent.com/7556264/193584080-8f615c78-1ac9-4d70-84f5-0c447f9a5eb2.png)

Assignment:
![image](https://user-images.githubusercontent.com/7556264/193582728-5fe00b84-bf79-4397-8a35-6134cae6782a.png)


Edit assignment parameters:

![image](https://user-images.githubusercontent.com/7556264/193582971-634bd1bf-a031-4dc4-b0db-2e1d5c5de45c.png)

**Comment by gettek** [comment]
Nice! Thanks @NikolaiKleppe, we can run further tests until the next release and please feel free to submit a pull request
