### ISSUE TITLE
Policy initiative set effect per policy definition 

### ISSUE THREAD

**Issue by mezzofix** [gettek/terraform-azurerm-policy-as-code#54]
Hello,

I'm unable to figure out how could I set the effects for each single policy definition inside a policy set when assigning that policy set to a scope. Right now, it looks that I can set one for the entire policy set. 

![This is what I'm looking for](https://user-images.githubusercontent.com/57439630/194104808-602966ec-578d-4058-807c-235c04d1c2db.png)

**Comment by gettek** [comment]
Hi @mezzofix 

You may set `merge_effects = false` or `merge_parameters = false` as seen in the initiative [readme](https://github.com/gettek/terraform-azurerm-policy-as-code/blob/main/modules/initiative/README.md).

**Comment by mezzofix** [comment]
Hi @gettek 

thank you ! Each policy definition within the Initiative is using a distinct effect parameter. Am I doing this correct (please see the screen shot). 
![obraz](https://user-images.githubusercontent.com/57439630/194595578-9f90be41-bbe2-4f41-a2f9-5772a4669696.png)

Many thanks !

**Comment by gettek** [comment]
Hi @mezzofix, are you using the initiative module? If so it will suffix "effect_" to each policy definition reference Id as seen [in this example](https://github.com/gettek/terraform-azurerm-policy-as-code/blob/main/examples/assignments_org.tf#L71). In your screen shot above it looks like you are using the parameter `displayName` which is incorrect, but if you are using a built-in initiative you can refer to its parameter names in the definition structure itself.
