### ISSUE TITLE
Role Assignment behavior with User Assigned Managed Identity

### ISSUE THREAD

**Issue by ashkuren** [gettek/terraform-azurerm-policy-as-code#64]
Hi @gettek ,

I would like to know if the behavior below is intended with regards to the variable `skip_role_assignment`.
When we specify `identity_ids` (User Assigned Managed Identity), Role Assignments are never made.

https://github.com/gettek/terraform-azurerm-policy-as-code/blob/88f1afed29503bff637830a919fb74ab2a08e151/modules/def_assignment/variables.tf#L162-L165

In this piece of code, `local.role_definition_ids` is always `[]` as `local.identity_type == UserAssigned`.

Should the Role Assignments be independent of Identity Type used?

**Comment by gettek** [comment]
Hi, yes this intentional as mentioned in the [ReadMe here](https://github.com/gettek/terraform-azurerm-policy-as-code#role-assignments). User Managed Identities will likely have their role assignments configured independently hence shifting this responsibility away from the module.
