### ISSUE TITLE
Set Assignment - Display Name and Description Variables are ignored

### ISSUE THREAD

**Issue by birdnathan** [gettek/terraform-azurerm-policy-as-code#71]
# Issue Template

## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Context
The assignment_display_name and assignment_description parameters are ignored and always default to " "

* Module Version: 2.7.2
* Terraform Version: 1.4.2
* AzureRM Provider Version: 3.49.0

```hcl
data "azurerm_role_definition" "log_analytics_contributor" {
  name = "Log Analytics Contributor"
}

data "azurerm_role_definition" "monitoring_contributor" {
  name = "Monitoring Contributor"
}

module "diagnostics_assignment" {
  source     = "gettek/policy-as-code/azurerm//modules/set_assignment"
  initiative = module.diagnostics_initiative

  assignment_scope        = "/subscriptions/GUID"
  assignment_effect       = "DeployIfNotExists"
  assignment_display_name = "DIAGNOSTICS - Deploy Diagnostic Settings to Azure Services"
  assignment_description  = "This policy set deploys the configurations of application Azure resources to forward diagnostic logs and metrics to an Azure Log Analytics workspace. See the list of policies of the services that are included"
  assignment_parameters = {
    "logAnalytics" = "/subscriptions/GUID/resourceGroups/RG-NAME/providers/Microsoft.OperationalInsights/workspaces/ala01"
  }

  role_definition_ids = [
    "/subscriptions/GUID${data.azurerm_role_definition.log_analytics_contributor.role_definition_id}",
    "/subscriptions/GUID${data.azurerm_role_definition.monitoring_contributor.role_definition_id}"
  ]

  depends_on = [
    module.diagnostics_initiative
  ]
}
```

## Expected Behavior
These values should be honoured

## Current Behavior
Defaults to ""

## Failure Information (for bugs)
the coelsce logic in https://github.com/gettek/terraform-azurerm-policy-as-code/blob/2.7.2/modules/set_assignment/variables.tf doesnt seem to work, always defaults to "".

<img width="285" alt="image" src="https://user-images.githubusercontent.com/42775203/228529430-bc77c1eb-f2ac-411e-b4e0-5bc5073c093a.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/42775203/228529832-dae4ec39-c470-4ba5-8b51-15c04f358fbc.png">

**Comment by gettek** [comment]
Hi @birdnathan thanks for raising this, appears the default values in those variables need to be removed for the coalesce to work correctly, will fix in the next release

**Comment by birdnathan** [comment]
@gettek Nearly. Only works if i remove var.initiative.display_name and var.initiative.description from lines 145 and 146 in variables.tf - https://github.com/gettek/terraform-azurerm-policy-as-code/blob/2.7.3/modules/set_assignment/variables.tf

display_name    = try(coalesce(var.assignment_display_name), "")
description     = try(coalesce(var.assignment_description), "")

I did try to update the variables in this file in the branch too but still doesnt work - https://github.com/gettek/terraform-azurerm-policy-as-code/blob/2.7.3/modules/initiative/variables.tf

**Comment by gettek** [comment]
@birdnathan, I can't seem to replicate this issue, the plan from [this commit](https://github.com/gettek/terraform-azurerm-policy-as-code/commit/b34a22f8bee5b085c2867a8f10d322b910c1d39d) gives the desired result:

- [def_assignment](https://github.com/gettek/terraform-azurerm-policy-as-code/actions/runs/4563755317/jobs/8052639502#step:5:7102)
- [set_assignment](https://github.com/gettek/terraform-azurerm-policy-as-code/actions/runs/4563755317/jobs/8052639502#step:5:5760)

Can you confirm your current setup please

**Comment by birdnathan** [comment]
@gettek 
```hcl
module "diagnostics_policies" {
  for_each        = fileset("./Policies/Diagnostics", "*")
  source          = "gettek/policy-as-code/azurerm//modules/definition"
  policy_name     = trimsuffix(each.value, ".json")
  policy_category = "Diagnostics"
}

module "diagnostics_initiative" {
  source                  = "gettek/policy-as-code/azurerm//modules/initiative"
  initiative_name         = "XXX-Deploy-Diagnostics-LogAnalytics"
  initiative_display_name = "[XXX] Deploy Diagnostic Settings to Azure Services"
  initiative_description  = "This policy set deploys the configurations of application Azure resources to forward diagnostic logs and metrics to an Azure Log Analytics workspace. See the list of policies of the services that are included "
  initiative_category     = "Diagnostics"



  member_definitions = [
    for pol in module.diagnostics_policies :
    pol.definition
  ]

  depends_on = [
    module.diagnostics_policies
  ]
}

data "azurerm_role_definition" "log_analytics_contributor" {
  name = "Log Analytics Contributor"
}

data "azurerm_role_definition" "monitoring_contributor" {
  name = "Monitoring Contributor"
}

module "diagnostics_assignment" {
  //source = "gettek/policy-as-code/azurerm//modules/set_assignment"
  source     = "./modules/set_assignment" //points to copy of 2.7.3
  initiative = module.diagnostics_initiative

  assignment_scope        = "/subscriptions/GUID"
  assignment_effect       = "DeployIfNotExists"
  assignment_display_name = "DIAGNOSTICS - Deploy Diagnostic Settings to Azure Services"
  assignment_description  = "This policy set deploys the configurations of application Azure resources to forward diagnostic logs and metrics to an Azure Log Analytics workspace. See the list of policies of the services that are included"
  assignment_parameters = {
    "logAnalytics" = "/subscriptionsGUID/resourceGroups/RG-NAME/providers/Microsoft.OperationalInsights/workspaces/LA-NAME"
  }

  role_definition_ids = [
    "/subscriptions/GUID${data.azurerm_role_definition.log_analytics_contributor.role_definition_id}",
    "/subscriptions/GUID${data.azurerm_role_definition.monitoring_contributor.role_definition_id}"
  ]

  depends_on = [
    module.diagnostics_initiative
  ]
}
```

**Comment by birdnathan** [comment]
Thanks @gettek - good spot. All working as expected.
