### ISSUE TITLE
Location argument isn't being set when creating a policy assignment

### ISSUE THREAD

**Issue by colina1777** [gettek/terraform-azurerm-policy-as-code#83]
# Issue Template

## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Context

* Module Version: 2.8.1
* Terraform Version: 1.4.6
* AzureRM Provider Version: 3.60.0

```hcl
module "service_bus_policy_test" {
  source            = "gettek/policy-as-code/azurerm//modules/def_assignment"
  version           = "2.8.1"
  definition        = data.azurerm_policy_definition.example
  assignment_scope  = data.azurerm_management_group.example.id
  assignment_name   = data.azurerm_policy_definition.example.name
  assignment_effect = "Deny"
  assignment_location = local.assignment_location
}

locals {
   assignment_location = "uksouth"
}
```

## Expected Behavior
The Location of the policy assignment should be set to uksouth.

## Current Behavior
The location argument isn't set when I run a plan/apply. I tried creating the assignment without the assignment_location input originally to use "uksouth" set in the module but this fails to set the location when a plan is run. This behaviour also exists in version 2.8.0. When I revert back to 2.7.2 the location is set correctly. I've tried using previous AzureRM versions but get the same results as above.

Thanks in advance,
C.

**Comment by gettek** [comment]
Hi @colina1777

`location` is only used for DINE/Modify policies containing an Identity, [see here](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#identity)

This parameter is redundant for all other effects.
